<a href="https://colab.research.google.com/github/Hugekyung/NLP/blob/master/%5B2020_08_20%5D_%ED%8F%89%EA%B0%80%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1번

In [ ]:
import numpy as np

In [ ]:
# matrix 수동 생성
matrix = [[0, 0.5, 0, 0.5], [0.5, 0, 0, 0.5], [0, 0, 0, 1.0], [0.333, 0.333, 0.333, 0]]
matrix = np.array(matrix)
matrix

array([[0.   , 0.5  , 0.   , 0.5  ],
       [0.5  , 0.   , 0.   , 0.5  ],
       [0.   , 0.   , 0.   , 1.   ],
       [0.333, 0.333, 0.333, 0.   ]])

In [ ]:
d = 0.85
B_vertex_score = (1-d) + d * (0.5 + 0.333)

In [ ]:
B_vertex_score

0.85805

## 2번

In [ ]:
doc_ls = ['바나나 사과 포도 포도',
         '사과 포도',
         '포도 바나나',
         '짜장면 짬뽕 탕수육',
         '볶음밥 탕수육',
         '짜장면 짬뽕',
         '라면 스시',
         '스시',
         '가츠동 스시 소바',
         '된장찌개 김치찌개 김치',
         '김치 된장',
         '비빔밥 김치'
         ]

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD

tfidf_vector = TfidfVectorizer()
tfidf_vector

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [ ]:
tfidf = tfidf_vector.fit_transform(doc_ls)
print(tfidf)

  (0, 15)	0.7806870451028085
  (0, 9)	0.4418867148991048
  (0, 6)	0.4418867148991048
  (1, 15)	0.662044442799776
  (1, 9)	0.7494645793884686
  (2, 15)	0.662044442799776
  (2, 6)	0.7494645793884686
  (3, 14)	0.5773502691896258
  (3, 13)	0.5773502691896258
  (3, 12)	0.5773502691896258
  (4, 7)	0.7586307126040724
  (4, 14)	0.6515208683486948
  (5, 13)	0.7071067811865476
  (5, 12)	0.7071067811865476
  (6, 11)	0.6043946600096447
  (6, 5)	0.7966850663542188
  (7, 11)	1.0
  (8, 10)	0.6231128431839633
  (8, 0)	0.6231128431839633
  (8, 11)	0.47271637301705055
  (9, 1)	0.47271637301705055
  (9, 2)	0.6231128431839633
  (9, 4)	0.6231128431839633
  (10, 3)	0.7966850663542188
  (10, 1)	0.6043946600096447
  (11, 8)	0.7966850663542188
  (11, 1)	0.6043946600096447


In [ ]:
# 특이값 분해
svd = TruncatedSVD(n_components=4)
svd

TruncatedSVD(algorithm='randomized', n_components=4, n_iter=5,
             random_state=None, tol=0.0)

In [ ]:
u = svd.fit_transform(tfidf)
u

array([[ 1.00000000e+00, -5.23076396e-17, -4.30520923e-18,
        -2.50904815e-17],
       [ 8.48027961e-01,  1.38582527e-17,  9.22199117e-17,
         9.88972765e-17],
       [ 8.48027961e-01, -1.30058930e-16, -9.41827445e-17,
        -9.19420603e-17],
       [-6.93889390e-18, -1.13764157e-14,  9.74417029e-01,
         2.96417303e-16],
       [ 3.12250226e-17, -4.80829065e-15,  4.07721810e-01,
        -3.09689719e-16],
       [ 0.00000000e+00, -1.03282083e-14,  8.85014956e-01,
         4.51262163e-16],
       [ 4.16333634e-17,  8.00147095e-01,  9.23692115e-15,
         3.53931108e-17],
       [ 5.55111512e-17,  8.86398340e-01,  1.02122482e-14,
        -1.41572443e-16],
       [ 9.71445147e-17,  7.03397990e-01,  7.69743430e-15,
        -1.06179332e-16],
       [ 2.77555756e-17, -3.84663252e-16, -1.09485246e-15,
         6.91474173e-01],
       [ 0.00000000e+00,  1.15398976e-16,  2.86860905e-16,
         7.57603151e-01],
       [ 0.00000000e+00, -3.84663252e-17, -1.52992483e-16,
      

In [ ]:
svd.components_[0].argsort()

array([ 8,  3, 10, 12, 13,  2, 14,  5,  1,  7,  4, 11,  0,  9,  6, 15],
      dtype=int64)

In [ ]:
words = tfidf_vector.get_feature_names()
topic = [words[j] for j in svd.components_[i].argsort()[:-4:-1]]
topic

['김치', '된장', '비빔밥']

In [ ]:
print('상위 토픽 단어는 :', topic)

상위 토픽 단어는 : ['김치', '된장', '비빔밥']


## 3번

In [ ]:
doc_ls = ['바나나 사과 포도 포도',
         '사과 포도',
         '포도 바나나',
         '짜장면 짬뽕 탕수육',
         '볶음밥 탕수육',
         '짜장면 짬뽕',
         '라면 스시',
         '스시',
         '가츠동 스시 소바',
         '된장찌개 김치찌개 김치',
         '김치 된장',
         '비빔밥 김치'
         ]

In [ ]:
from gensim import corpora
from gensim.models import LdaModel, TfidfModel

## 4번

In [ ]:
class Car():
    car_count = 0
    
    def __init__(self, name, CC, product_year):
        self.name = name
        self.CC = CC
        self.product_year = product_year
        Car.car_count += 1
        print('총 등록된 차량개수 : {}대'.format(Car.car_count))
        
    def Change_Name(self, new_name):
        self.name = new_name
        
        return self.name
    
    def Print_CC():
        if self.CC > 2000:
            print('대형')
        elif 1000 < self.CC < 2000:
            print('중형')
        else:
            print('소형')
        
    

In [ ]:
car1 = Car('sm3', '2000', '2016')
print(car1.Change_Name('pride'))
car2 = Car('gv80', '3000', '2020')

총 등록된 차량개수 : 1대
pride
총 등록된 차량개수 : 2대
