<a href="https://colab.research.google.com/github/Hugekyung/NLP/blob/master/NLP_test_tkyang.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 문제 1

In [ ]:
import numpy as np
import pandas as pd
from collections import defaultdict

d1 = "우리반은 마라탕을 좋아해"
d2 = "우리반은 마라탕을 더 이상 먹지않을거야 그래도 마라탕을 좋아해"

In [ ]:
docs = []
docs.append(d1)
docs.append(d2)

print(docs)

for d in docs:
    docs_tokens = d.split()
docs_tokens = np.unique(docs_tokens)
docs_tokens

['우리반은 마라탕을 좋아해', '우리반은 마라탕을 더 이상 먹지않을거야 그래도 마라탕을 좋아해']


array(['그래도', '더', '마라탕을', '먹지않을거야', '우리반은', '이상', '좋아해'], dtype='<U6')

In [ ]:
words = defaultdict(lambda : len(words))
[words[token] for token in docs_tokens]
len(words)

7

In [ ]:
TDM = np.zeros((len(words), len(docs)), dtype=int)
for i, doc in enumerate(docs):
    for token in doc.split():
        TDM[words[token], i] += 1
TDM

array([[0, 1],
       [0, 1],
       [1, 2],
       [0, 1],
       [1, 1],
       [0, 1],
       [1, 1],
       [0, 0]])

## 문제2

In [ ]:
d1 = "우리반은 마라탕을 좋아해"
d2 = "우리반은 마라탕을 더 이상 먹지않을거야 그래도 마라탕을 좋아해"
d1_token = d1.split()
d2_token = d2.split()
d_uni = docs_tokens
d_uni

array(['그래도', '더', '마라탕을', '먹지않을거야', '우리반은', '이상', '좋아해'], dtype='<U6')

In [ ]:
# tf
tf1 = []

for i in range(len(d_uni)):
    tf1.append(d1_token.count(d_uni[i]))

tf2 = []
for i in range(len(d_uni)):
    tf2.append(d2_token.count(d_uni[i]))

tf1 = np.array(tf1)
tf2 = np.array(tf2)
print(tf1, tf2)

TF = []
TF2 = []
for i in range(len(tf1)):
    TF.append(tf1[i]/len(d1_token))
for i in range(len(tf1)):
    TF2.append(tf2[i]/len(d2_token))
TF = np.array(TF)
TF2 = np.array(TF2)
print(TF, TF2)

[0 0 1 0 1 0 1] [1 1 2 1 1 1 1]
[0.         0.         0.33333333 0.         0.33333333 0.
 0.33333333] [0.125 0.125 0.25  0.125 0.125 0.125 0.125]


In [ ]:
# df
df1 = []

for i in range(len(d_uni)):
    df = 0
    if d_uni[i] in d1_token and d_uni[i] in d2_token:
        df += 2
        df1.append(df)
    elif d_uni[i] in d1_token or d_uni[i] in d2_token:
        df += 1
        df1.append(df)
df1 = np.array(df1)
df1

array([1, 1, 2, 1, 2, 1, 2])

In [ ]:
# idf
from math import log
N = len(docs)
IDF = np.log(N/df1)
IDF

array([0.69314718, 0.69314718, 0.        , 0.69314718, 0.        ,
       0.69314718, 0.        ])

In [ ]:
# TF-IDF
print(TF * IDF)
print(TF2 * IDF)

[0. 0. 0. 0. 0. 0. 0.]
[0.0866434 0.0866434 0.        0.0866434 0.        0.0866434 0.       ]


## 문제 3

In [ ]:
d1 = "우리반은 마라탕을 좋아해"
d2 = "우리반은 마라탕을 더 이상 먹지않을거야 그래도 마라탕을 좋아해"

In [ ]:
# 자카드 유사도
union = set(d1_token).union(d2_token)
intersection = set(d1_token).intersection(d2_token)

zaccard = len(intersection) / len(union)
zaccard

0.42857142857142855

## 문제 4

log
log
log
log
exp
exp