<a href="https://colab.research.google.com/github/Hugekyung/NLP/blob/master/TF_IDF_%EA%B5%AC%ED%98%84_%EB%B3%B5%EC%8A%B5_(2020_07_26).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from math import log
import numpy as np

In [2]:
d1 = "The cat sat on my face I hate a cat"
d2 = "The dog sat on my bed I love a dog"

In [3]:
d1_tokens = d1.split()
d2_tokens = d2.split()
d3_tokens = d1_tokens + d2_tokens
print(d1_tokens)
print(d2_tokens)
print(d3_tokens)
t_uni = np.unique(d3_tokens)
print(t_uni)

['The', 'cat', 'sat', 'on', 'my', 'face', 'I', 'hate', 'a', 'cat']
['The', 'dog', 'sat', 'on', 'my', 'bed', 'I', 'love', 'a', 'dog']
['The', 'cat', 'sat', 'on', 'my', 'face', 'I', 'hate', 'a', 'cat', 'The', 'dog', 'sat', 'on', 'my', 'bed', 'I', 'love', 'a', 'dog']
['I' 'The' 'a' 'bed' 'cat' 'dog' 'face' 'hate' 'love' 'my' 'on' 'sat']


TF : 특정 문서내 토큰등장빈도 = 토큰빈도 / 문서내 전체 토큰 개수

In [29]:
# d1문서내 토큰빈도 수 구하기
tf1 = []

for i in range(len(t_uni)):
    tf = d1_tokens.count(t_uni[i])
    tf1.append(tf)
# print(t_uni)
tf1 = np.array(tf1)
tf1

array([1, 1, 1, 0, 2, 0, 1, 1, 0, 1, 1, 1])

In [28]:
# d2문서내 토큰빈도 수 구하기
tf2 = []

for i in range(len(t_uni)):
    tf = d2_tokens.count(t_uni[i])
    tf2.append(tf)
# print(t_uni)
tf2 = np.array(tf2)
tf2

array([1, 1, 1, 1, 0, 2, 0, 0, 1, 1, 1, 1])

In [31]:
# TF 구하기
TF1 = []
for i in range(len(tf1)):
    TF1.append(tf1[i] / len(d1_tokens))
TF1 = np.array(TF1)
TF1

array([0.1, 0.1, 0.1, 0. , 0.2, 0. , 0.1, 0.1, 0. , 0.1, 0.1, 0.1])

In [32]:
# TF 구하기
TF2 = []
for i in range(len(tf2)):
    TF2.append(tf2[i] / len(d2_tokens))
TF2 = np.array(TF2)
TF2

array([0.1, 0.1, 0.1, 0.1, 0. , 0.2, 0. , 0. , 0.1, 0.1, 0.1, 0.1])

DF : 특정 토큰이 등장한 문서 수

In [33]:
# 각 단어가 d1과 d2에 등장했는지 -> 1 or 2
df1 = []
for i in range(len(t_uni)):
    df = 0
    if t_uni[i] in d1_tokens and t_uni[i] in d2_tokens:
        df += 2
        df1.append(df)
    elif t_uni[i] in d1_tokens or t_uni[i] in d2_tokens:
        df += 1
        df1.append(df)
# print(d1_tokens)
# print(d2_tokens)
# print(t_uni)
df1 = np.array(df1)
df1

array([2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2])

IDF : log(N / (1 + DF))

In [38]:
N = 2
idf = np.log(2 / (df1))
idf

array([0.        , 0.        , 0.        , 0.69314718, 0.69314718,
       0.69314718, 0.69314718, 0.69314718, 0.69314718, 0.        ,
       0.        , 0.        ])

TF-IDF

In [39]:
# d1문서
tfidf1 = TF1 * idf
tfidf1

array([0.        , 0.        , 0.        , 0.        , 0.13862944,
       0.        , 0.06931472, 0.06931472, 0.        , 0.        ,
       0.        , 0.        ])

In [40]:
# d2문서
tfidf2 = TF2 * idf
tfidf2

array([0.        , 0.        , 0.        , 0.06931472, 0.        ,
       0.13862944, 0.        , 0.        , 0.06931472, 0.        ,
       0.        , 0.        ])

In [48]:
result = pd.DataFrame(t_uni)
result.rename({0:'토큰'},axis=1,inplace = True)
result['tfidf1'] = tfidf1
result['tfidf2'] = tfidf2

In [49]:
result

토큰    tfidf1    tfidf2
0      I  0.000000  0.000000
1    The  0.000000  0.000000
2      a  0.000000  0.000000
3    bed  0.000000  0.069315
4    cat  0.138629  0.000000
5    dog  0.000000  0.138629
6   face  0.069315  0.000000
7   hate  0.069315  0.000000
8   love  0.000000  0.069315
9     my  0.000000  0.000000
10    on  0.000000  0.000000
11   sat  0.000000  0.000000