<a href="https://colab.research.google.com/github/Hugekyung/NLP/blob/master/Topic_Modeling_LSA(%EC%9E%A0%EC%9E%AC%EC%9D%98%EB%AF%B8%EB%B6%84%EC%84%9D).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from collections import defaultdict

doc_ls = ['바나나 사과 포도 포도 짜장면',
          '사과 포도',
          '포도 바나나',
          '짜장면 짬뽕 탕수육',
          '볶음밥 탕수육',
          '짜장면 짬뽕',
          '라면 스시',
          '스시 짜장면',
          '가츠동 스시 소바',
          '된장찌개 김치찌개 김치',
          '김치 된장 짜장면',
          '비빔밥 김치'
          ]
tokens = []
for i in range(len(doc_ls)):
    tokens.append(doc_ls[i].split())

uni_token = []
for i,v in enumerate(tokens):
    for j, val in enumerate(v):
        uni_token.append(val)
uni_token = np.unique(uni_token)
print(len(uni_token))
print(doc_ls)

16
['바나나 사과 포도 포도 짜장면', '사과 포도', '포도 바나나', '짜장면 짬뽕 탕수육', '볶음밥 탕수육', '짜장면 짬뽕', '라면 스시', '스시 짜장면', '가츠동 스시 소바', '된장찌개 김치찌개 김치', '김치 된장 짜장면', '비빔밥 김치']


In [2]:
# 각 고유 토큰에 인덱스 지정
word2id = defaultdict(lambda : len(word2id))
[word2id[token] for token in uni_token]

id2word = { word2id[k]:k for k in word2id.keys()}
len(word2id)


16

In [6]:
id2word

{0: '가츠동',
 1: '김치',
 2: '김치찌개',
 3: '된장',
 4: '된장찌개',
 5: '라면',
 6: '바나나',
 7: '볶음밥',
 8: '비빔밥',
 9: '사과',
 10: '소바',
 11: '스시',
 12: '짜장면',
 13: '짬뽕',
 14: '탕수육',
 15: '포도'}

In [7]:
len(word2id)

16

In [8]:
# DTM생성

# Matrix생성 16 x 12
TDM = np.zeros((len(word2id), len(doc_ls)), dtype=int)
print(TDM)
for i, doc in enumerate(doc_ls):
    print(doc)
    for t in doc.split():
        TDM[word2id[t], i] += 1

len(TDM)


[[0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]]
바나나 사과 포도 포도 짜장면
사과 포도
포도 바나나
짜장면 짬뽕 탕수육
볶음밥 탕수육
짜장면 짬뽕
라면 스시
스시 짜장면
가츠동 스시 소바
된장찌개 김치찌개 김치
김치 된장 짜장면
비빔밥 김치


16

In [9]:
# U, s, VT = np.linalg.svd(TDM[:-1].T)
# print(U)
topic_num = 4
from sklearn.decomposition import randomized_svd
U, s, VT = randomized_svd(TDM.T,
                              n_components=topic_num,
                              n_iter=10,
                              random_state=None)
U

array([[ 0.79909178, -0.23631699,  0.01005289,  0.01866414],
       [ 0.32422891, -0.2375544 ,  0.02301229,  0.05619723],
       [ 0.32422891, -0.2375544 ,  0.02301229,  0.05619723],
       [ 0.21208198,  0.48565893, -0.12813175, -0.43005064],
       [ 0.02526658,  0.12189092, -0.05545517, -0.21541789],
       [ 0.18924633,  0.38413621, -0.08554157, -0.26853634],
       [ 0.02364425,  0.12564719, -0.32779721,  0.36853889],
       [ 0.17200336,  0.34344312, -0.2877235 ,  0.18258982],
       [ 0.02646113,  0.15718219, -0.46966719,  0.55314475],
       [ 0.02972694,  0.20690983,  0.548939  ,  0.37187387],
       [ 0.19323187,  0.45209802,  0.33628631,  0.12275337],
       [ 0.0265624 ,  0.16539812,  0.38312378,  0.24776514]])

In [10]:
U[:,:4]

array([[ 0.79909178, -0.23631699,  0.01005289,  0.01866414],
       [ 0.32422891, -0.2375544 ,  0.02301229,  0.05619723],
       [ 0.32422891, -0.2375544 ,  0.02301229,  0.05619723],
       [ 0.21208198,  0.48565893, -0.12813175, -0.43005064],
       [ 0.02526658,  0.12189092, -0.05545517, -0.21541789],
       [ 0.18924633,  0.38413621, -0.08554157, -0.26853634],
       [ 0.02364425,  0.12564719, -0.32779721,  0.36853889],
       [ 0.17200336,  0.34344312, -0.2877235 ,  0.18258982],
       [ 0.02646113,  0.15718219, -0.46966719,  0.55314475],
       [ 0.02972694,  0.20690983,  0.548939  ,  0.37187387],
       [ 0.19323187,  0.45209802,  0.33628631,  0.12275337],
       [ 0.0265624 ,  0.16539812,  0.38312378,  0.24776514]])

In [11]:
np.sum(s[:4])/np.sum(s) # (4,4)행렬 안에 가지고 있는  정보량이 약 56% 정도 된다

1.0

In [12]:
print(VT)

[[ 0.0082077   0.07739641  0.00922069  0.0599366   0.00922069  0.00733397
   0.34843127  0.00783718  0.00823912  0.34843127  0.0082077   0.06889362
   0.48563449  0.12448389  0.0736207   0.69686254]
 [ 0.06425309  0.33700147  0.0845808   0.18480907  0.0845808   0.05136218
  -0.19370961  0.04982669  0.06761161 -0.19370961  0.06425309  0.25600828
   0.58415588  0.3555557   0.24835482 -0.38741921]
 [-0.22621639  0.61090353  0.26439785  0.16197315  0.26439785 -0.15788435
   0.01592593 -0.02671012  0.18453253  0.01592593 -0.22621639 -0.52268348
  -0.07468389 -0.10291629 -0.0884251   0.03185185]
 [ 0.27669846  0.37136542  0.1860217   0.06140467  0.1860217   0.18435345
   0.03744775 -0.10775805  0.12393905  0.03744775  0.27669846  0.55238845
  -0.18737521 -0.34945274 -0.3228814   0.07489549]]


In [13]:
V = VT.T[:,:4]
V

array([[ 0.0082077 ,  0.06425309, -0.22621639,  0.27669846],
       [ 0.07739641,  0.33700147,  0.61090353,  0.37136542],
       [ 0.00922069,  0.0845808 ,  0.26439785,  0.1860217 ],
       [ 0.0599366 ,  0.18480907,  0.16197315,  0.06140467],
       [ 0.00922069,  0.0845808 ,  0.26439785,  0.1860217 ],
       [ 0.00733397,  0.05136218, -0.15788435,  0.18435345],
       [ 0.34843127, -0.19370961,  0.01592593,  0.03744775],
       [ 0.00783718,  0.04982669, -0.02671012, -0.10775805],
       [ 0.00823912,  0.06761161,  0.18453253,  0.12393905],
       [ 0.34843127, -0.19370961,  0.01592593,  0.03744775],
       [ 0.0082077 ,  0.06425309, -0.22621639,  0.27669846],
       [ 0.06889362,  0.25600828, -0.52268348,  0.55238845],
       [ 0.48563449,  0.58415588, -0.07468389, -0.18737521],
       [ 0.12448389,  0.3555557 , -0.10291629, -0.34945274],
       [ 0.0736207 ,  0.24835482, -0.0884251 , -0.3228814 ],
       [ 0.69686254, -0.38741921,  0.03185185,  0.07489549]])

In [14]:
topic1 = []
topic2 = []
topic3 = []
topic4 = []

for i in range(len(id2word)):
    topic1.append(V[i][0])
    topic2.append(V[i][1])
    topic3.append(V[i][2])
    topic4.append(V[i][3])

for i in range(len(topic1)):
    print('topic1_word : {} / 중요도 : {}'.format(id2word[i], topic1[i]))
    print('topic2_word : {} / 중요도 : {}'.format(id2word[i], topic2[i]))
    print('topic3_word : {} / 중요도 : {}'.format(id2word[i], topic3[i]))
    print('topic4_word : {} / 중요도 : {}'.format(id2word[i], topic4[i]))
    print('=====================================================')

V_max = np.apply_along_axis(lambda a: np.max(a), 0, V) # 각 열의 최대값을 구한다
V_max
# for i in range(len(topic1)):
#     if 
#     print('word : {} / 중요도 : {}'.format(id2word[i], topic1[i]))

topic1_word : 가츠동 / 중요도 : 0.008207704762125151
topic2_word : 가츠동 / 중요도 : 0.06425308724872597
topic3_word : 가츠동 / 중요도 : -0.22621638508821168
topic4_word : 가츠동 / 중요도 : 0.2766984641841515
topic1_word : 김치 / 중요도 : 0.07739641277516954
topic2_word : 김치 / 중요도 : 0.3370014719129778
topic3_word : 김치 / 중요도 : 0.6109035277294065
topic4_word : 김치 / 중요도 : 0.3713654174050663
topic1_word : 김치찌개 / 중요도 : 0.009220692812438385
topic2_word : 김치찌개 / 중요도 : 0.08458080012362988
topic3_word : 김치찌개 / 중요도 : 0.2643978491951754
topic4_word : 김치찌개 / 중요도 : 0.186021703956787
topic1_word : 된장 / 중요도 : 0.05993660204089402
topic2_word : 된장 / 중요도 : 0.18480906658701754
topic3_word : 된장 / 중요도 : 0.1619731471621054
topic4_word : 된장 / 중요도 : 0.06140466805460927
topic1_word : 된장찌개 / 중요도 : 0.009220692812438385
topic2_word : 된장찌개 / 중요도 : 0.0845808001236299
topic3_word : 된장찌개 / 중요도 : 0.2643978491951754
topic4_word : 된장찌개 / 중요도 : 0.18602170395678677
topic1_word : 라면 / 중요도 : 0.007333965980468623
topic2_word : 라면 / 중요도 : 0.0513621810356

array([0.69686254, 0.58415588, 0.61090353, 0.55238845])