<a href="https://colab.research.google.com/github/Hugekyung/NLP/blob/master/Word2Vec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

CBoW

In [ ]:
import numpy as np
from keras_preprocessing.text import Tokenizer
from keras.utils import to_categorical

text = 'you will never know until you try'
tokens = text.split()
uni_tokens = np.unique(tokens)
uni_tokens

array(['know', 'never', 'try', 'until', 'will', 'you'], dtype='<U5')

In [ ]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

# 예제 데이터 배열
values = array(tokens)

# 문자열에 숫자를 붙임
label_enc = LabelEncoder()
int_enc = label_enc.fit_transform(values)

# binary encode
onehot_enc = OneHotEncoder(sparse=False)
int_enc = int_enc.reshape(len(int_enc), 1) # n:1 matrix로 변환
onehot_enc = onehot_enc.fit_transform(int_enc)
print(onehot_enc)

[[0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0.]]


In [ ]:
# W초기화
Hidden_node = 4
W1 = np.random.randn(len(uni_tokens), Hidden_node)
W2 = np.random.randn(Hidden_node,len(uni_tokens))

In [ ]:
# y가 you, Xt+1 = will
X = onehot_enc
Y = X[0]

Xt_1 = X[1]
H = np.dot(Xt_1, W1)
H = H.reshape(4,1)

In [ ]:
def softmax(x):
    return np.exp(x) / sum(np.exp(x))

o = softmax(np.dot(W2.T, H))

In [ ]:
o

array([[0.1037768 ],
       [0.26769512],
       [0.52473957],
       [0.02298816],
       [0.00655838],
       [0.07424198]])

In [ ]:
Y = Y.reshape(6,1)

In [ ]:
# CrossEntropy
loss = -(np.sum(Y * np.log(o)))
loss

15.628485435851399

In [ ]:
o = o-Y
o
# Y = Y.reshape(6,1)

array([[ 0.1037768 ],
       [ 0.26769512],
       [ 0.52473957],
       [ 0.02298816],
       [ 0.00655838],
       [-0.92575802]])